const CLIENT_ID="4765b89201b44558a7d5141f9b93c178";
const REDIRECT_URI=location.origin+location.pathname;
const SCOPES=["streaming","user-read-email","user-read-private","user-read-playback-state","user-modify-playback-state"].join(" ");
const firebaseConfig={apiKey:"AIzaSyCcquz1mpz3FsmFFBKgJLgpbkHCajTUpzY",authDomain:"hitster-bingo-cb792.firebaseapp.com",databaseURL:"https://hitster-bingo-cb792-default-rtdb.europe-west1.firebasedatabase.app",projectId:"hitster-bingo-cb792",storageBucket:"hitster-bingo-cb792.firebasestorage.app",messagingSenderId:"98696776977",appId:"1:98696776977:web:e797e555e2d9b38bcc99b0"};
const COLORS=[{key:"yellow",name:"GEEL",emoji:"🟨",input:"cat-yellow",hex:"#ffd21f"},{key:"pink",name:"ROZE",emoji:"🩷",input:"cat-pink",hex:"#ff4f93"},{key:"purple",name:"PAARS",emoji:"🟪",input:"cat-purple",hex:"#8d35ff"},{key:"blue",name:"BLAUW",emoji:"🟦",input:"cat-blue",hex:"#19a8ff"},{key:"green",name:"GROEN",emoji:"🟩",input:"cat-green",hex:"#62d321"}];
let db, player, deviceId="", accessToken=localStorage.spotify_access_token||"", refreshToken=localStorage.spotify_refresh_token||"", expiresAt=Number(localStorage.spotify_expires_at||0);
let tracks=JSON.parse(localStorage.hb_csv_tracks||"[]"), currentTrack=null, currentRoomCode="", currentRoundId="", currentPlayerId=localStorage.hb_player_id||"", currentPlayerName=localStorage.hb_player_name||"", activeRound=null;
let stopTimer=null, lockTimer=null, screenTimer=null, audioCtx=null, lastBingoKey=localStorage.hb_last_bingo_key||"";
const $=id=>document.getElementById(id);
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]));
const pick=a=>a[Math.floor(Math.random()*a.length)];
const emoji=k=>({yellow:"🟨",pink:"🩷",purple:"🟪",blue:"🟦",green:"🟩",free:"⭐"}[k]||"⬜");

function init(){if(!firebase.apps.length)firebase.initializeApp(firebaseConfig);db=firebase.database();wire();handleRedirect().then(updateStatus);setupPlayerMode();restoreHost();}
function wire(){
 $("loginBtn")?.addEventListener("click",login);$("logoutBtn")?.addEventListener("click",logout);$("activateBtn")?.addEventListener("click",activatePlayer);$("csvFile")?.addEventListener("change",handleCsv);$("resetUsedBtn")?.addEventListener("click",()=>{delete localStorage.hb_used;updateStatus()});
 $("newRoomBtn")?.addEventListener("click",createRoom);$("soundBtn")?.addEventListener("click",activateSound);$("startRoundBtn")?.addEventListener("click",startRound);$("playBtn")?.addEventListener("click",playHidden);$("stopBtn")?.addEventListener("click",stopPlayback);$("showAnswerBtn")?.addEventListener("click",showAnswer);$("lockBtn")?.addEventListener("click",lockRound);$("publishBtn")?.addEventListener("click",publishResults);
 $("joinBtn")?.addEventListener("click",joinPlayer);$("readyBtn")?.addEventListener("click",setReady);$("scoreReadyBtn")?.addEventListener("click",setReady);$("submitAnswerBtn")?.addEventListener("click",submitAnswer);
 $("hostScoreboard")?.addEventListener("click",scoreboardClick);
}

// CSV
function parseCSV(t){let rows=[],r=[],c="",q=false;for(let i=0;i<t.length;i++){let ch=t[i],n=t[i+1];if(ch=='"'&&q&&n=='"'){c+='"';i++}else if(ch=='"')q=!q;else if(ch==","&&!q){r.push(c);c=""}else if((ch=="\n"||ch=="\r")&&!q){if(ch=="\r"&&n=="\n")i++;r.push(c);c="";if(r.some(v=>v.trim()))rows.push(r);r=[]}else c+=ch}r.push(c);if(r.some(v=>v.trim()))rows.push(r);return rows}
function norm(h){return h.toLowerCase().replace(/[^a-z0-9]/g,"")}function findI(h,n){let ns=h.map(norm);for(let x of n){let i=ns.indexOf(norm(x));if(i>=0)return i}return -1}
function tid(u){let m=String(u||"").match(/spotify:track:([a-zA-Z0-9]+)/)||String(u||"").match(/track\/([a-zA-Z0-9]+)/);return m?m[1]:(/^[a-zA-Z0-9]{15,}$/.test(String(u).trim())?String(u).trim():"")}
function handleCsv(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{loadCsv(r.result)}catch(err){alert(err.message)}};r.readAsText(f)}
function loadCsv(text){let rows=parseCSV(text),h=rows[0]||[],ui=findI(h,["Track URI","Spotify URI","URI"]),ti=findI(h,["Track Name","Name","Title"]),ai=findI(h,["Artist Name(s)","Artist Names","Artists","Artist"]),al=findI(h,["Album Name","Album"]),ri=findI(h,["Release Date","Release"]),di=findI(h,["Duration (ms)","Duration"]);if(ui<0||ti<0||ai<0)throw Error("CSV mist Track URI, Track Name of Artist Name(s).");let out=[],seen=new Set();for(let i=1;i<rows.length;i++){let row=rows[i],id=tid(row[ui]);if(!id||seen.has(id))continue;seen.add(id);out.push({id,uri:"spotify:track:"+id,name:row[ti]||"Onbekend",artists:row[ai]||"Onbekend",album:al>=0?row[al]||"":"",release_date:ri>=0?row[ri]||"":"",duration_ms:Number(row[di])||180000})}tracks=out;localStorage.hb_csv_tracks=JSON.stringify(tracks);updateStatus()}
function chooseTrack(){if(!tracks.length)return null;let u=new Set(JSON.parse(localStorage.hb_used||"[]")),a=$("noRepeat").checked?tracks.filter(t=>!u.has(t.id)):tracks;if(!a.length){u.clear();a=tracks}let t=pick(a);u.add(t.id);localStorage.hb_used=JSON.stringify([...u]);updateStatus();return t}

// Spotify
function rand(l){let ch="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~",o="";crypto.getRandomValues(new Uint8Array(l)).forEach(x=>o+=ch[x%ch.length]);return o}
async function sha(s){return crypto.subtle.digest("SHA-256",new TextEncoder().encode(s))}function b64(b){return btoa(String.fromCharCode(...new Uint8Array(b))).replace(/=/g,"").replace(/\+/g,"-").replace(/\//g,"_")}
async function login(){let v=rand(96);localStorage.spotify_code_verifier=v;location="https://accounts.spotify.com/authorize?"+new URLSearchParams({response_type:"code",client_id:CLIENT_ID,scope:SCOPES,code_challenge_method:"S256",code_challenge:b64(await sha(v)),redirect_uri:REDIRECT_URI})}
async function handleRedirect(){let code=new URLSearchParams(location.search).get("code");if(!code)return;let v=localStorage.spotify_code_verifier;let res=await fetch("https://accounts.spotify.com/api/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:CLIENT_ID,grant_type:"authorization_code",code,redirect_uri:REDIRECT_URI,code_verifier:v})});let d=await res.json();if(d.access_token){saveTokens(d);history.replaceState({},document.title,REDIRECT_URI)}else alert("Spotify login fout")}
function saveTokens(d){accessToken=d.access_token;if(d.refresh_token)refreshToken=d.refresh_token;expiresAt=Date.now()+d.expires_in*1000-60000;localStorage.spotify_access_token=accessToken;if(refreshToken)localStorage.spotify_refresh_token=refreshToken;localStorage.spotify_expires_at=expiresAt}
async function getToken(){if(accessToken&&Date.now()<expiresAt)return accessToken;if(!refreshToken)return"";let res=await fetch("https://accounts.spotify.com/api/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"refresh_token",refresh_token:refreshToken,client_id:CLIENT_ID})});let d=await res.json();if(d.access_token){saveTokens(d);return accessToken}return""}
async function api(url,opt={}){let t=await getToken();if(!t)throw Error("Niet ingelogd.");let r=await fetch(url,{...opt,headers:{...(opt.headers||{}),Authorization:"Bearer "+t,"Content-Type":"application/json"}});if(r.status===204)return{};let d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error?.message||"Spotify fout");return d}
function logout(){["spotify_access_token","spotify_refresh_token","spotify_expires_at"].forEach(k=>localStorage.removeItem(k));accessToken=refreshToken="";expiresAt=0;updateStatus()}
async function updateStatus(){if($("csvStatus"))$("csvStatus").textContent=tracks.length?`${tracks.length} nummers geladen.`:"Nog geen CSV geladen.";if(!$("loginStatus"))return;if(await getToken()){try{let me=await api("https://api.spotify.com/v1/me");$("loginStatus").textContent="Ingelogd als: "+(me.display_name||me.email||"Spotify gebruiker");$("activateBtn").disabled=false}catch(e){$("loginStatus").textContent="Ingelogd."}}else{$("loginStatus").textContent="Nog niet ingelogd."; $("activateBtn").disabled=true}}
window.onSpotifyWebPlaybackSDKReady=()=>{};
async function activatePlayer(){let t=await getToken();if(!t){alert("Login eerst.");return}if(!window.Spotify){alert("Spotify speler nog niet geladen.");return}if(player){await player.connect();return}player=new Spotify.Player({name:"Hitster Bingo",getOAuthToken:async cb=>cb(await getToken()),volume:.8});player.addListener("ready",({device_id})=>{deviceId=device_id;$("loginStatus").textContent+=" — speler actief."});await player.connect()}

// Room/player
function getCats(){return{yellow:$("cat-yellow").value,pink:$("cat-pink").value,purple:$("cat-purple").value,blue:$("cat-blue").value,green:$("cat-green").value}}
function roomCode(){let c="",ch="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";for(let i=0;i<4;i++)c+=ch[Math.floor(Math.random()*ch.length)];return c}
function genCard(){let p=[],cs=["yellow","pink","purple","blue","green"];for(let i=0;i<24;i++)p.push(cs[i%5]);for(let i=p.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[p[i],p[j]]=[p[j],p[i]]}let card=[],k=0;for(let i=0;i<25;i++)card.push(i===12?"free":p[k++]);return card}
function createRoom(){currentRoomCode=roomCode();db.ref("rooms/"+currentRoomCode).set({createdAt:firebase.database.ServerValue.TIMESTAMP,categories:getCats()}).then(()=>{localStorage.hb_host_room=currentRoomCode;showRoom();listenHost(currentRoomCode);listenBingo(currentRoomCode)})}
function showRoom(){$("roomBox").classList.remove("hidden");$("roomCodeText").textContent=currentRoomCode;$("joinLink").value=location.origin+location.pathname+"?room="+currentRoomCode}
function restoreHost(){let room=localStorage.hb_host_room;if(room&&!new URLSearchParams(location.search).get("room")){currentRoomCode=room;showRoom();listenHost(room);listenBingo(room)}}
function setupPlayerMode(){let room=new URLSearchParams(location.search).get("room");if(!room)return;document.body.classList.add("playerMode");$("modeText").textContent="Speler";$("playerApp").classList.remove("hidden");currentRoomCode=room.toUpperCase();$("playerRoomCode").textContent=currentRoomCode;if(currentPlayerName)$("playerNameInput").value=currentPlayerName}
function joinPlayer(){let name=$("playerNameInput").value.trim();if(!name){alert("Vul je naam in.");return}currentPlayerName=name;if(!currentPlayerId)currentPlayerId="p_"+Math.random().toString(36).slice(2,10)+Date.now().toString(36).slice(-4);localStorage.hb_player_id=currentPlayerId;localStorage.hb_player_name=name;localStorage.hb_player_room=currentRoomCode;let ref=db.ref("rooms/"+currentRoomCode+"/players/"+currentPlayerId);ref.once("value").then(s=>{let ex=s.val()||{};return ref.update({name,online:true,ready:false,joinedAt:ex.joinedAt||firebase.database.ServerValue.TIMESTAMP,lastSeen:firebase.database.ServerValue.TIMESTAMP,card:ex.card||genCard(),marked:ex.marked||{}})}).then(()=>{ref.child("online").onDisconnect().set(false);listenPlayer();showScreen("screenLobby")})}
function setReady(){if(!currentPlayerId)return;db.ref("rooms/"+currentRoomCode+"/players/"+currentPlayerId+"/ready").set(true)}
function showScreen(id){document.querySelectorAll("#playerApp .screen").forEach(s=>s.classList.add("hidden"));$(id)?.classList.remove("hidden")}

// Host listen
function listenHost(room){db.ref("rooms/"+room).on("value",s=>{let data=s.val()||{};renderHostPlayers(data);renderHostScore(data);hostReadyState(data)})}
function renderHostPlayers(room){let ps=room.players||{};$("hostPlayers").innerHTML=Object.values(ps).length?Object.values(ps).map(p=>`<div class="playerRow ${p.ready?"ready":""}"><strong>${esc(p.name)}</strong><span>${p.ready?"✅ READY":"⏳ wacht"}</span></div>`).join(""):"Nog geen spelers."}
function allReady(room){let ps=Object.values(room.players||{});return ps.length>0&&ps.every(p=>p.ready)}
function hostReadyState(room){let r=room.currentRound||{},btn=$("startRoundBtn");if(["picking","ready","answering","locked"].includes(r.status))return;if(allReady(room)){btn.disabled=false;btn.textContent="🎲 START RONDE";$("hostStatus").textContent="Iedereen is READY."}else{btn.disabled=true;btn.textContent="⏳ Wachten op READY";let not=Object.values(room.players||{}).filter(p=>!p.ready).map(p=>p.name).join(", ");$("hostStatus").textContent=not?"Nog niet ready: "+not:"Wachten op spelers."}}

// Round host
function flash(){let f=document.createElement("div");f.className="flash";document.body.appendChild(f);setTimeout(()=>f.remove(),700)}
function pickerHTML(mode){return mode==="wheel"?`<div class="wheelWrap"><div class="pointer"></div><div class="wheel"></div></div><div class="pickerTitle">Draairad draait...</div>`:`<div class="discoIcon">🪩</div><div class="pickerTitle">Discobal kiest...</div>`}
function startRound(){let room=currentRoomCode;if(!room){alert("Maak eerst kamer.");return}db.ref("rooms/"+room).once("value").then(s=>{let data=s.val()||{};if(!allReady(data)){alert("Nog niet iedereen is READY.");return}currentTrack=chooseTrack();if(!currentTrack){alert("Upload eerst CSV.");return}let up={};Object.keys(data.players||{}).forEach(pid=>up["rooms/"+room+"/players/"+pid+"/ready"]=false);db.ref().update(up).then(()=>startRoundVisual(room))})}
function startRoundVisual(room){
  $("hostAnswerArea").innerHTML="";
  $("playBtn").disabled=true;
  $("showAnswerBtn").disabled=true;
  const mode=Math.random()<.5?"disco":"wheel";
  $("hostPickerArea").innerHTML=pickerHTML(mode);
  currentRoundId="r_"+Date.now();

  db.ref("rooms/"+room+"/currentRound").set({
    id:currentRoundId,
    status:"picking",
    pickerMode:mode,
    seconds:Number($("duration").value)||20,
    createdAt:firebase.database.ServerValue.TIMESTAMP
  });

  setTimeout(()=>{
    flash();
    let color=pick(COLORS),cat=$(color.input).value||"Geen categorie";
    $("hostPickerArea").innerHTML=`<div class="colorDisplay">${color.emoji}<br>${color.name}</div><div class="categoryDisplay">${esc(cat)}</div>`;
    let round={id:currentRoundId,status:"ready",pickerMode:mode,colorKey:color.key,colorName:color.name,colorEmoji:color.emoji,category:cat,seconds:Number($("duration").value)||20};
    db.ref("rooms/"+room+"/currentRound").set(round);
    $("playBtn").disabled=false;
    $("showAnswerBtn").disabled=false;
    $("hostScorePanel").classList.remove("hidden");
  },2600);
}
async function playHidden(){if(!currentTrack)return;$("playBtn").disabled=true;if(!deviceId){await activatePlayer();await new Promise(r=>setTimeout(r,1200))}if(!deviceId){alert("Geen Spotify-speler actief.");$("playBtn").disabled=false;return}let dur=(Number($("duration").value)||20)*1000,pos=0;if($("randomStart").checked&&currentTrack.duration_ms>dur+40000){let max=Math.max(0,currentTrack.duration_ms-dur-5000);pos=Math.floor(20000+Math.random()*Math.max(1,max-20000))}await api(`https://api.spotify.com/v1/me/player/play?device_id=${deviceId}`,{method:"PUT",body:JSON.stringify({uris:[currentTrack.uri],position_ms:pos})});let deadline=Date.now()+dur;await db.ref("rooms/"+currentRoomCode+"/currentRound").update({status:"answering",deadlineMs:deadline});$("stopBtn").disabled=false;clearTimeout(lockTimer);lockTimer=setTimeout(lockRound,dur);clearTimeout(stopTimer);stopTimer=setTimeout(stopPlayback,dur)}
async function stopPlayback(){try{await api("https://api.spotify.com/v1/me/player/pause",{method:"PUT",body:"{}"})}catch(e){}$("stopBtn").disabled=true}
function lockRound(){db.ref("rooms/"+currentRoomCode+"/currentRound/status").set("locked")}
function showAnswer(){if(!currentTrack)return;let ans={track:currentTrack.name,artist:currentTrack.artists,album:currentTrack.album,year:(currentTrack.release_date||"").slice(0,4)};$("hostAnswerArea").innerHTML=`<div class="correctBox"><h3>${esc(ans.track)}</h3><p>${esc(ans.artist)}</p><p>${esc(ans.album||"-")} — ${esc(ans.year||"-")}</p></div>`;db.ref("rooms/"+currentRoomCode+"/currentRound").update({correctAnswer:ans})}
function renderHostScore(room){let r=room.currentRound||{};if(!r.id)return;$("hostScorePanel").classList.remove("hidden");$("hostRoundInfo").textContent=`${r.colorEmoji||""} ${r.colorName||""} — ${r.category||""} — ${r.status||""}`;let ps=room.players||{},ans=room.answers?.[r.id]||{},cor=room.correct?.[r.id]||{};$("hostScoreboard").innerHTML=Object.entries(ps).map(([pid,p])=>{let st=cor[pid],cls=st===true?"scoreGood":st===false?"scoreBad":"scorePending";return `<div class="scoreCard ${cls}"><div>${esc(p.name)}</div><div>${esc(ans[pid]?.answer||"Geen antwoord")}</div><div><button type="button" class="goodBtn ${st===true?"goodSelected":""}" data-pid="${pid}" data-good="true">✅</button><button type="button" class="badBtn ${st===false?"badSelected":""}" data-pid="${pid}" data-good="false">❌</button></div></div>`}).join("")}
function scoreboardClick(e){let btn=e.target.closest("button[data-pid]");if(!btn)return;e.preventDefault();let pid=btn.dataset.pid,good=btn.dataset.good==="true";db.ref("rooms/"+currentRoomCode+"/currentRound").once("value").then(s=>{let r=s.val()||{};if(!r.id)throw Error("Geen actieve ronde.");return db.ref("rooms/"+currentRoomCode+"/correct/"+r.id+"/"+pid).set(good)}).then(()=>{$("hostStatus").textContent="✅ Beoordeling opgeslagen."}).catch(err=>alert(err.message))}
function publishResults(){db.ref("rooms/"+currentRoomCode).once("value").then(s=>{let room=s.val()||{},up={};up["rooms/"+currentRoomCode+"/currentRound/status"]="judged";Object.keys(room.players||{}).forEach(pid=>up["rooms/"+currentRoomCode+"/players/"+pid+"/ready"]=false);return db.ref().update(up)}).then(()=>{$("hostStatus").textContent="Resultaten verzonden. Goede spelers mogen kiezen."})}

// Player listen/render
function listenPlayer(){db.ref("rooms/"+currentRoomCode).on("value",s=>{let room=s.val()||{},r=room.currentRound||{};activeRound=r;renderLobby(room);if(!r.id){showScreen("screenLobby");return}if(r.status==="picking"){renderPlayerPicker(r);showScreen("screenPicker");return}if(r.status==="ready"){renderColor(r);showScreen("screenColor");return}if(r.status==="answering"){renderAnswer(room,r);showScreen("screenAnswer");return}if(r.status==="locked"){renderScore(room);showScreen("screenScore");return}if(r.status==="judged"){renderScore(room);let me=room.players?.[currentPlayerId]||{},good=room.correct?.[r.id]?.[currentPlayerId]===true,picked=me.lastPickedRound===r.id;if(good&&!picked){renderPick(room,r);showScreen("screenPick")}else showScreen("screenScore")}});listenBingo(currentRoomCode)}
function renderLobby(room){let ps=room.players||{},me=ps[currentPlayerId]||{};$("playerList").innerHTML=Object.entries(ps).map(([pid,p])=>`<div class="playerRow ${p.ready?"ready":""}" onclick="showOther('${pid}')"><strong>${esc(p.name)}${pid===currentPlayerId?" (jij)":""}</strong><span>${p.ready?"✅ READY":"⏳ wacht"}</span></div>`).join("");let total=Object.keys(ps).length,ready=Object.values(ps).filter(p=>p.ready).length;$("lobbyInfo").textContent=`${ready}/${total} spelers ready`;renderCard("ownCard",me.card||[],me.marked||{});$("readyBtn").disabled=!!me.ready}
function showOther(pid){db.ref("rooms/"+currentRoomCode+"/players/"+pid).once("value").then(s=>{let p=s.val();if(!p)return;$("otherCardBox").classList.remove("hidden");$("otherCardTitle").textContent="Kaart van "+p.name;renderCard("otherCard",p.card||[],p.marked||{})})}
window.showOther=showOther;
function renderCard(id,card,marked,click=false,r=null){let el=$(id);if(!el)return;el.innerHTML=(card||[]).map((c,i)=>{let m=marked&&marked[i],pickable=click&&r&&c===r.colorKey&&c!=="free"&&!m,blocked=click&&!pickable&&c!=="free"&&!m;return `<div class="bingoCell ${c==="free"?"free":""} ${pickable?"pickableCell":""} ${blocked?"blockedCell":""}" data-i="${i}">${m?"✅":emoji(c)}</div>`}).join("");if(click)el.querySelectorAll(".pickableCell").forEach(x=>x.addEventListener("click",()=>pickCell(Number(x.dataset.i))))}
function renderPlayerPicker(r){$("playerPickerArea").innerHTML=pickerHTML(r.pickerMode||"disco")}
function renderColor(r){$("colorDisplay").innerHTML=`${r.colorEmoji}<br>${r.colorName}`;$("categoryDisplay").textContent=r.category}
function renderAnswer(room,r){$("answerRoundInfo").textContent=`${r.colorEmoji} ${r.colorName} — ${r.category}`;let ex=room.answers?.[r.id]?.[currentPlayerId];if(ex){$("answerInput").value=ex.answer;$("answerInput").disabled=true;$("submitAnswerBtn").disabled=true;$("answerStatus").textContent="🔒 Antwoord ingeleverd."}else{$("answerInput").disabled=false;$("submitAnswerBtn").disabled=false;$("answerStatus").textContent="Typ je antwoord."}clearInterval(screenTimer);screenTimer=setInterval(()=>{let left=Math.max(0,Math.ceil(((r.deadlineMs||0)-Date.now())/1000));$("timerBox").textContent="⏱️ "+left+" sec";if(left<=0){clearInterval(screenTimer);$("answerInput").disabled=true;$("submitAnswerBtn").disabled=true}},300)}
function submitAnswer(){if(!activeRound?.id)return;db.ref("rooms/"+currentRoomCode+"/answers/"+activeRound.id+"/"+currentPlayerId).set({answer:$("answerInput").value||"",submittedAt:firebase.database.ServerValue.TIMESTAMP}).then(()=>showScreen("screenScore"))}
function renderScore(room){let r=room.currentRound||{},box=$("correctAnswerBox"),ans=r.correctAnswer;if(ans){box.classList.remove("hidden");box.innerHTML=`<h3>✅ Juiste antwoord</h3><p>🎵 ${esc(ans.track||"-")}</p><p>👤 ${esc(ans.artist||"-")}</p><p>📅 ${esc(ans.year||"-")}</p><p>💿 ${esc(ans.album||"-")}</p>`}else box.classList.add("hidden");let ps=room.players||{},answers=room.answers?.[r.id]||{},cor=room.correct?.[r.id]||{};$("playerScoreboard").innerHTML=Object.entries(ps).map(([pid,p])=>{let st=r.status==="judged"?cor[pid]:undefined,cls=st===true?"scoreGood":st===false?"scoreBad":"scorePending",icon=st===true?"✅":st===false?"❌":"⏳";return `<div class="scoreCard ${cls}"><div class="scoreName" onclick="showOther('${pid}')">${esc(p.name)}${pid===currentPlayerId?" (jij)":""}</div><div>${esc(answers[pid]?.answer||"Geen antwoord")}</div><div>${icon}</div></div>`}).join("")}
function renderPick(room,r){let me=room.players?.[currentPlayerId]||{};$("pickInfo").textContent=`Kies 1 ${r.colorEmoji} ${r.colorName} vakje.`;renderCard("pickCard",me.card||[],me.marked||{},true,r)}
function checkBingo(marked){let lines=[[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24],[0,5,10,15,20],[1,6,11,16,21],[2,7,12,17,22],[3,8,13,18,23],[4,9,14,19,24],[0,6,12,18,24],[4,8,12,16,20]];return lines.some(line=>line.every(i=>i===12||(marked&&marked[i])))}
function pickCell(i){db.ref("rooms/"+currentRoomCode+"/players/"+currentPlayerId).once("value").then(s=>{let p=s.val()||{},marked=p.marked||{},card=p.card||[];if(card[i]!==activeRound.colorKey||marked[i])return;marked[i]=true;let bingo=checkBingo(marked);db.ref("rooms/"+currentRoomCode+"/players/"+currentPlayerId).update({marked,bingo,lastPickedRound:activeRound.id,ready:true}).then(()=>{if(bingo)db.ref("rooms/"+currentRoomCode+"/bingos").push({name:currentPlayerName,roundId:activeRound.id,at:firebase.database.ServerValue.TIMESTAMP});showScreen("screenLobby")})})}

// Audio/winner
function activateSound(){try{let C=window.AudioContext||window.webkitAudioContext;if(C&&!audioCtx)audioCtx=new C();if(audioCtx&&audioCtx.state==="suspended")audioCtx.resume();$("soundStatus").textContent="✅ Host-geluid actief."}catch(e){}}
function tune(){try{let C=window.AudioContext||window.webkitAudioContext;if(!audioCtx&&C)audioCtx=new C();if(!audioCtx)return;[523,659,784,1046].forEach((f,i)=>{let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=f;o.connect(g);g.connect(audioCtx.destination);let t=audioCtx.currentTime+i*.18;g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(.3,t+.03);g.gain.exponentialRampToValueAtTime(.001,t+.16);o.start(t);o.stop(t+.18)})}catch(e){}}
function speak(name){try{speechSynthesis.cancel();let u=new SpeechSynthesisUtterance("Aiiii mi hende. Speler "+name+" heeft bingo!");u.lang="nl-NL";u.rate=.9;speechSynthesis.speak(u)}catch(e){}}
function confetti(){let cs=["#ffd21f","#ff4f93","#8d35ff","#19a8ff","#62d321","#fff"];for(let i=0;i<90;i++){let p=document.createElement("div");p.className="confetti";p.style.left=Math.random()*100+"vw";p.style.background=pick(cs);document.body.appendChild(p);setTimeout(()=>p.remove(),3500)}}
function showWinner(name){if($("winnerPanel")){$("winnerPanel").classList.remove("hidden");$("winnerMessage").innerHTML="🏆 BINGO!<br>Speler "+esc(name)+" heeft gewonnen!"}if($("hostBingoPanel")){$("hostBingoPanel").classList.remove("hidden");$("hostBingoMessage").innerHTML="🏆 BINGO!<br>Speler "+esc(name)+" heeft gewonnen!"}confetti();tune();setTimeout(()=>speak(name),700)}
function listenBingo(room){db.ref("rooms/"+room+"/bingos").on("child_added",s=>{let b=s.val()||{},key=s.key+"_"+(b.roundId||"");if(key===lastBingoKey)return;lastBingoKey=key;localStorage.hb_last_bingo_key=key;showWinner(b.name||"onbekend")})}

init();
