const CLIENT_ID="4765b89201b44558a7d5141f9b93c178";
const REDIRECT_URI=window.location.origin+window.location.pathname;
const SCOPES=["streaming","user-read-email","user-read-private","user-read-playback-state","user-modify-playback-state"].join(" ");
const firebaseConfig={apiKey:"AIzaSyCcquz1mpz3FsmFFBKgJLgpbkHCajTUpzY",authDomain:"hitster-bingo-cb792.firebaseapp.com",databaseURL:"https://hitster-bingo-cb792-default-rtdb.europe-west1.firebasedatabase.app",projectId:"hitster-bingo-cb792",storageBucket:"hitster-bingo-cb792.firebasestorage.app",messagingSenderId:"98696776977",appId:"1:98696776977:web:e797e555e2d9b38bcc99b0"};
const colors=[{key:"yellow",name:"GEEL",emoji:"🟨",input:"cat-yellow",hex:"#ffd21f"},{key:"pink",name:"ROZE",emoji:"🩷",input:"cat-pink",hex:"#ff4f93"},{key:"purple",name:"PAARS",emoji:"🟪",input:"cat-purple",hex:"#8d35ff"},{key:"blue",name:"BLAUW",emoji:"🟦",input:"cat-blue",hex:"#19a8ff"},{key:"green",name:"GROEN",emoji:"🟩",input:"cat-green",hex:"#62d321"}];

let db, player, deviceId="", accessToken=localStorage.spotify_access_token||"", refreshToken=localStorage.spotify_refresh_token||"", expiresAt=Number(localStorage.spotify_expires_at||0);
let tracks=JSON.parse(localStorage.hb_csv_tracks||"[]"), currentTrack=null, stopTimer=null, lockTimer=null;
let currentRoomCode="", currentRoundId="", selectedColor=null, currentPlayerId=localStorage.hb_player_id||"", currentPlayerName=localStorage.hb_player_name||"", activeRound=null, screenTimerInterval=null;
let lastBingoKey=localStorage.hb_last_bingo_key||"", hostSoundReady=false;

const $=id=>document.getElementById(id);
const pick=a=>a[Math.floor(Math.random()*a.length)];
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]));
const emoji=k=>({yellow:"🟨",pink:"🩷",purple:"🟪",blue:"🟦",green:"🟩",free:"⭐"}[k]||"⬜");
function showError(msg){console.error(msg);alert(msg)}

// CSV
function parseCSV(t){const rows=[];let r=[],c="",q=false;for(let i=0;i<t.length;i++){const ch=t[i],n=t[i+1];if(ch=='"'&&q&&n=='"'){c+='"';i++}else if(ch=='"')q=!q;else if(ch==","&&!q){r.push(c);c=""}else if((ch=="\n"||ch=="\r")&&!q){if(ch=="\r"&&n=="\n")i++;r.push(c);c="";if(r.some(v=>v.trim()))rows.push(r);r=[]}else c+=ch}r.push(c);if(r.some(v=>v.trim()))rows.push(r);return rows}
function norm(h){return h.toLowerCase().replace(/[^a-z0-9]/g,"")}function findI(h,names){const ns=h.map(norm);for(const n of names){const i=ns.indexOf(norm(n));if(i>=0)return i}return -1}
function tid(u){if(!u)return"";let m=u.match(/spotify:track:([a-zA-Z0-9]+)/)||u.match(/track\/([a-zA-Z0-9]+)/);if(m)return m[1];return /^[a-zA-Z0-9]{15,}$/.test(u.trim())?u.trim():""}
function loadCsvText(text){const rows=parseCSV(text),h=rows[0]||[],ui=findI(h,["Track URI","Spotify URI","URI"]),ti=findI(h,["Track Name","Name","Title"]),ai=findI(h,["Artist Name(s)","Artist Names","Artists","Artist"]),al=findI(h,["Album Name","Album"]),ri=findI(h,["Release Date","Release"]),di=findI(h,["Duration (ms)","Duration"]);if(ui<0||ti<0||ai<0)throw Error("CSV mist Track URI, Track Name of Artist Name(s).");const out=[],seen=new Set();for(let r=1;r<rows.length;r++){const row=rows[r],id=tid(row[ui]||"");if(!id||seen.has(id))continue;seen.add(id);let dur=di>=0?Number(row[di]):180000;out.push({id,uri:"spotify:track:"+id,name:row[ti]||"Onbekend",artists:row[ai]||"Onbekend",album:al>=0?row[al]||"","release_date":ri>=0?row[ri]||"":"",duration_ms:Number.isFinite(dur)&&dur>0?dur:180000})}tracks=out;localStorage.hb_csv_tracks=JSON.stringify(tracks);updateStatus()}
function handleCsvFile(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{loadCsvText(r.result)}catch(err){alert("CSV laden mislukt: "+err.message)}};r.readAsText(f)}
function usedSet(){return new Set(JSON.parse(localStorage.hb_used||"[]"))}function saveUsed(s){localStorage.hb_used=JSON.stringify([...s])}
function chooseTrack(){if(!tracks.length)return null;const u=usedSet();let a=$("noRepeat").checked?tracks.filter(t=>!u.has(t.id)):tracks;if(!a.length){u.clear();a=tracks}const t=pick(a);u.add(t.id);saveUsed(u);updateStatus();return t}

// Spotify
function randomString(l){const ch="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~";let o="";crypto.getRandomValues(new Uint8Array(l)).forEach(x=>o+=ch[x%ch.length]);return o}async function sha256(p){return crypto.subtle.digest("SHA-256",new TextEncoder().encode(p))}function b64(b){return btoa(String.fromCharCode(...new Uint8Array(b))).replace(/=/g,"").replace(/\+/g,"-").replace(/\//g,"_")}
async function login(){const v=randomString(96);localStorage.spotify_code_verifier=v;const c=b64(await sha256(v));location="https://accounts.spotify.com/authorize?"+new URLSearchParams({response_type:"code",client_id:CLIENT_ID,scope:SCOPES,code_challenge_method:"S256",code_challenge:c,redirect_uri:REDIRECT_URI})}
async function handleRedirect(){const p=new URLSearchParams(location.search),code=p.get("code");if(!code)return;const v=localStorage.spotify_code_verifier;if(!v){showError("Geen code_verifier. Login opnieuw.");return}const res=await fetch("https://accounts.spotify.com/api/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:CLIENT_ID,grant_type:"authorization_code",code,redirect_uri:REDIRECT_URI,code_verifier:v})});const data=await res.json().catch(()=>({}));if(data.access_token){saveTokens(data);delete localStorage.spotify_code_verifier;history.replaceState({},document.title,REDIRECT_URI);await updateStatus()}else showError("Spotify token fout: "+JSON.stringify(data))}
function saveTokens(d){accessToken=d.access_token;if(d.refresh_token)refreshToken=d.refresh_token;expiresAt=Date.now()+d.expires_in*1000-60000;localStorage.spotify_access_token=accessToken;if(refreshToken)localStorage.spotify_refresh_token=refreshToken;localStorage.spotify_expires_at=String(expiresAt)}
async function getToken(){if(accessToken&&Date.now()<expiresAt)return accessToken;if(!refreshToken)return"";const res=await fetch("https://accounts.spotify.com/api/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"refresh_token",refresh_token:refreshToken,client_id:CLIENT_ID})});const d=await res.json();if(d.access_token){saveTokens(d);return accessToken}return""}
async function api(url,opt={}){const t=await getToken();if(!t)throw Error("Niet ingelogd met Spotify.");const res=await fetch(url,{...opt,headers:{...(opt.headers||{}),Authorization:"Bearer "+t,"Content-Type":"application/json"}});if(res.status===204)return{};const d=await res.json().catch(()=>({}));if(!res.ok)throw Error(d.error?.message||JSON.stringify(d));return d}
function logout(){["spotify_access_token","spotify_refresh_token","spotify_expires_at"].forEach(k=>localStorage.removeItem(k));accessToken=refreshToken="";expiresAt=0;updateStatus()}
async function updateStatus(){if($("csvStatus"))$("csvStatus").textContent=tracks.length?`${tracks.length} nummers geladen.`:"Nog geen CSV geladen.";if(!$("loginStatus"))return;if(await getToken()){try{const me=await api("https://api.spotify.com/v1/me");$("loginStatus").textContent="Ingelogd als: "+(me.display_name||me.email||"Spotify gebruiker");$("activateBtn").disabled=false}catch(e){$("loginStatus").textContent="Ingelogd, maar profiel laden lukt niet."}}else{$("loginStatus").textContent="Nog niet ingelogd.";$("activateBtn").disabled=true}}
window.onSpotifyWebPlaybackSDKReady=()=>{};async function activatePlayer(){const t=await getToken();if(!t){alert("Login eerst.");return}if(!window.Spotify){alert("Spotify speler nog niet geladen.");return}if(player){await player.connect();return}player=new Spotify.Player({name:"Hitster Bingo Verborgen Speler",getOAuthToken:async cb=>cb(await getToken()),volume:.8});player.addListener("ready",({device_id})=>{deviceId=device_id;$("loginStatus").textContent+=" — speler actief."});player.addListener("account_error",({message})=>alert("Spotify Premium nodig of accountfout: "+message));player.addListener("authentication_error",({message})=>alert("Spotify login fout: "+message));await player.connect()}

// Firebase
function initFirebase(){try{if(!firebase.apps.length)firebase.initializeApp(firebaseConfig);db=firebase.database()}catch(e){showError("Firebase starten mislukt: "+e.message)}}
function roomCode(){const ch="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";let c="";for(let i=0;i<4;i++)c+=ch[Math.floor(Math.random()*ch.length)];return c}
function playerId(){return"p_"+Math.random().toString(36).slice(2,10)+Date.now().toString(36).slice(-4)}
function getCats(){return{yellow:$("cat-yellow").value.trim(),pink:$("cat-pink").value.trim(),purple:$("cat-purple").value.trim(),blue:$("cat-blue").value.trim(),green:$("cat-green").value.trim()}}
function genCard(){const p=[],cs=["yellow","pink","purple","blue","green"];for(let i=0;i<24;i++)p.push(cs[i%5]);for(let i=p.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[p[i],p[j]]=[p[j],p[i]]}const card=[];let k=0;for(let i=0;i<25;i++)card.push(i===12?"free":p[k++]);return card}

function createRoom(){currentRoomCode=roomCode();db.ref("rooms/"+currentRoomCode).set({createdAt:firebase.database.ServerValue.TIMESTAMP,status:"lobby",categories:getCats()}).then(()=>{localStorage.hb_host_room=currentRoomCode;showHostRoom(currentRoomCode);listenHost(currentRoomCode);listenBingo(currentRoomCode)}).catch(e=>showError("Kamer maken mislukt: "+e.message))}
function showHostRoom(code){$("roomInfo").classList.remove("hidden");$("roomCodeText").textContent=code;const url=location.origin+location.pathname+"?room="+encodeURIComponent(code);$("joinLink").value=url}
function listenHost(code){db.ref("rooms/"+code).on("value",s=>{const room=s.val()||{};renderHostPlayers(room);renderHostScore(room);hostReadyLock(room)})}
function renderHostPlayers(room){const players=room.players||{};$("playersList").innerHTML=Object.values(players).length?Object.values(players).map(p=>`<div class="screenPlayerRow ${p.ready?"ready":"notReady"}"><strong>${esc(p.name||"Speler")}</strong><span>${p.ready?"✅ READY":"⏳ wacht"}</span></div>`).join(""):"Nog geen spelers."}
function allReady(room){const list=Object.values(room.players||{});return list.length>0&&list.every(p=>p.ready)}
function hostReadyLock(room){const round=room.currentRound||{};if(["answering","locked"].includes(round.status))return;const btn=$("startBtn");if(!btn)return;if(!allReady(room)){btn.disabled=true;btn.textContent="⏳ Wachten op READY";const notReady=Object.values(room.players||{}).filter(p=>!p.ready).map(p=>p.name).join(", ");$("roundSyncStatus").textContent=notReady?"Nog niet ready: "+notReady:"Wachten op spelers."}else{btn.disabled=false;btn.textContent="🎲 START RONDE";$("roundSyncStatus").textContent="Iedereen is ready."}}

// Host round
function flash(){const f=document.createElement("div");f.className="flash";document.body.appendChild(f);setTimeout(()=>f.remove(),750)}
function startRound(){const room=currentRoomCode||localStorage.hb_host_room;if(!room){alert("Maak eerst een kamer.");return}db.ref("rooms/"+room).once("value").then(s=>{const data=s.val()||{};if(!allReady(data)){alert("Nog niet iedereen is READY.");return}currentTrack=chooseTrack();if(!currentTrack){alert("Upload eerst je CSV.");return}const updates={};Object.keys(data.players||{}).forEach(pid=>updates["rooms/"+room+"/players/"+pid+"/ready"]=false);db.ref().update(updates).then(()=>startRoundAfterReady(room))})}
function startRoundAfterReady(room){$("answerArea").innerHTML="";$("playBtn").disabled=true;$("answerBtn").disabled=true;const area=$("pickerArea"),mode=Math.random()<.5?"discobal":"rad";area.innerHTML=mode==="discobal"?`<div class="discoWrap"><div class="pickerTitle">🎉 Discobal kiest...</div><div class="disco"></div></div>`:`<div><div class="pickerTitle">🎡 Draairad draait...</div><div class="wheelWrap"><div class="pointer"></div><div class="wheel"></div></div></div>`;setTimeout(()=>{flash();selectedColor=pick(colors);const cat=$(selectedColor.input).value.trim()||"Geen categorie ingevuld";area.innerHTML=`<div class="reveal"><div class="colorDot" style="background:${selectedColor.hex};color:${selectedColor.hex}"></div><div class="colorName">${selectedColor.emoji} ${selectedColor.name}</div><div class="category">Categorie:<br><strong>${esc(cat)}</strong></div></div>`;currentRoundId="r_"+Date.now();const round={id:currentRoundId,status:"ready",createdAt:firebase.database.ServerValue.TIMESTAMP,seconds:Number($("duration").value)||20,colorKey:selectedColor.key,colorName:selectedColor.name,colorEmoji:selectedColor.emoji,category:cat};db.ref("rooms/"+room+"/currentRound").set(round);db.ref("rooms/"+room+"/rounds/"+currentRoundId).set(round);$("playBtn").disabled=false;$("answerBtn").disabled=false;$("hostScoreBox").classList.remove("hidden");$("roundSyncStatus").textContent="Ronde klaar. Start muziek om timer te laten lopen.";},2500)}
async function playHidden(){if(!currentTrack)return;$("playBtn").disabled=true;$("playBtn").textContent="🎵 Nummer speelt...";if(!deviceId){await activatePlayer();await new Promise(r=>setTimeout(r,1200))}if(!deviceId){alert("Geen Spotify-speler actief.");$("playBtn").disabled=false;return}const dur=(Number($("duration").value)||20)*1000;let pos=0;if($("randomStart").checked&&currentTrack.duration_ms>dur+40000){const max=Math.max(0,currentTrack.duration_ms-dur-5000);pos=Math.floor(20000+Math.random()*Math.max(1,max-20000))}try{await api(`https://api.spotify.com/v1/me/player/play?device_id=${deviceId}`,{method:"PUT",body:JSON.stringify({uris:[currentTrack.uri],position_ms:pos})});const room=currentRoomCode||localStorage.hb_host_room;const deadline=Date.now()+dur;await db.ref("rooms/"+room+"/currentRound").update({status:"answering",deadlineMs:deadline,startedAt:firebase.database.ServerValue.TIMESTAMP});await db.ref("rooms/"+room+"/rounds/"+currentRoundId).update({status:"answering",deadlineMs:deadline,startedAt:firebase.database.ServerValue.TIMESTAMP});$("stopBtn").disabled=false;clearTimeout(lockTimer);lockTimer=setTimeout(()=>lockRound(),dur);clearTimeout(stopTimer);stopTimer=setTimeout(stopPlayback,dur)}catch(e){alert("Afspelen mislukt: "+e.message);$("playBtn").disabled=false}}
async function stopPlayback(){clearTimeout(stopTimer);try{await api("https://api.spotify.com/v1/me/player/pause",{method:"PUT",body:"{}"})}catch(e){}$("stopBtn").disabled=true;$("playBtn").disabled=true;$("playBtn").textContent="🎵 Speel verborgen nummer"}
function lockRound(){const room=currentRoomCode||localStorage.hb_host_room;db.ref("rooms/"+room+"/currentRound/status").set("locked");$("roundSyncStatus").textContent="Antwoorden vergrendeld."}
function showAnswer(){if(!currentTrack)return;const ans={track:currentTrack.name||"",artist:currentTrack.artists||"",album:currentTrack.album||"",year:(currentTrack.release_date||"").slice(0,4)||"",shownAt:firebase.database.ServerValue.TIMESTAMP};$("answerArea").innerHTML=`<div class="answerCard"><h3>${esc(ans.track)}</h3><p><strong>Artiest:</strong> ${esc(ans.artist)}</p><p><strong>Album:</strong> ${esc(ans.album||"-")}</p><p><strong>Jaar:</strong> ${esc(ans.year||"-")}</p></div>`;const room=currentRoomCode||localStorage.hb_host_room;db.ref("rooms/"+room+"/currentRound").update({correctAnswer:ans,correctAnswerShown:true})}
function renderHostScore(room){const r=room.currentRound||{};if(!r.id)return;$("hostScoreBox").classList.remove("hidden");$("hostRoundInfo").textContent=`${r.colorEmoji||""} ${r.colorName||""} — ${r.category||""} — ${r.status||""}`;const ps=room.players||{},ans=room.answers?.[r.id]||{},cor=room.correct?.[r.id]||{};$("hostScoreboard").innerHTML=Object.entries(ps).map(([pid,p])=>{const st=cor[pid],cls=st===true?"scoreGood":st===false?"scoreBad":"scorePending";return `<div class="scoreCard ${cls}"><div class="scoreName">${esc(p.name||"Speler")}</div><div class="scoreAnswer">${esc(ans[pid]?.answer||"Geen antwoord")}</div><div><button class="goodBtn ${st===true?"goodSelected":""}" onclick="markAnswer('${pid}',true)">✅</button><button class="badBtn ${st===false?"badSelected":""}" onclick="markAnswer('${pid}',false)">❌</button></div></div>`}).join("")||"Nog geen spelers."}
function markAnswer(pid,good){const room=currentRoomCode||localStorage.hb_host_room;db.ref("rooms/"+room).once("value").then(s=>{const r=(s.val()||{}).currentRound||{};if(r.id)db.ref("rooms/"+room+"/correct/"+r.id+"/"+pid).set(good)})}
function publishResults(){const room=currentRoomCode||localStorage.hb_host_room;db.ref("rooms/"+room).once("value").then(s=>{const data=s.val()||{},r=data.currentRound||{};const up={};up["rooms/"+room+"/currentRound/status"]="judged";Object.keys(data.players||{}).forEach(pid=>up["rooms/"+room+"/players/"+pid+"/ready"]=false);db.ref().update(up);$("roundSyncStatus").textContent="Resultaten verzonden. Spelers kiezen eventueel vakje en klikken daarna READY."})}

// Player screens
function screenShow(id){document.querySelectorAll("#playerApp .screen").forEach(s=>s.classList.add("hidden"));$(id)?.classList.remove("hidden")}
function setupPlayer(){const room=new URLSearchParams(location.search).get("room");if(!room)return;document.body.classList.add("playerMode");currentRoomCode=room.toUpperCase();$("playerApp").classList.remove("hidden");$("screenRoomCode").textContent=currentRoomCode;if(currentPlayerName)$("screenNameInput").value=currentPlayerName;screenShow("screenJoin");if(localStorage.hb_player_room===currentRoomCode&&currentPlayerId&&currentPlayerName)joinPlayer(true)}
function joinPlayer(re=false){const name=($("screenNameInput").value||currentPlayerName||"").trim();if(!name){alert("Vul eerst je naam in.");return}if(!currentPlayerId)currentPlayerId=playerId();currentPlayerName=name;localStorage.hb_player_id=currentPlayerId;localStorage.hb_player_name=name;localStorage.hb_player_room=currentRoomCode;const ref=db.ref("rooms/"+currentRoomCode+"/players/"+currentPlayerId);ref.once("value").then(s=>{const ex=s.val()||{};return ref.update({name,online:true,ready:false,joinedAt:ex.joinedAt||firebase.database.ServerValue.TIMESTAMP,lastSeen:firebase.database.ServerValue.TIMESTAMP,card:ex.card||genCard(),marked:ex.marked||{}})}).then(()=>{ref.child("online").onDisconnect().set(false);ref.child("lastSeen").onDisconnect().set(firebase.database.ServerValue.TIMESTAMP);$("screenJoinStatus").textContent="Je doet mee!";listenPlayer();screenShow("screenLobby")}).catch(e=>showError("Meedoen mislukt: "+e.message))}
function listenPlayer(){db.ref("rooms/"+currentRoomCode).on("value",snap=>{const room=snap.val()||{},r=room.currentRound||{};activeRound=r;renderLobby(room);if(!r.id){screenShow("screenLobby");return}if(r.status==="ready"){renderColor(r);screenShow("screenColor");return}if(r.status==="answering"){renderAnswer(room,r);screenShow("screenAnswer");return}if(r.status==="locked"){renderScore(room);screenShow("screenScore");return}if(r.status==="judged"){renderScore(room);const me=room.players?.[currentPlayerId]||{},good=room.correct?.[r.id]?.[currentPlayerId]===true,picked=me.lastPickedRound===r.id;if(good&&!picked){renderPick(room,r);screenShow("screenPick")}else screenShow("screenScore")}});listenBingo(currentRoomCode)}
function renderLobby(room){const ps=room.players||{},me=ps[currentPlayerId]||{};$("lobbyPlayers").innerHTML=Object.entries(ps).map(([pid,p])=>`<div class="screenPlayerRow ${p.ready?"ready":"notReady"}" onclick="showOtherCard('${pid}')"><strong>${esc(p.name||"Speler")}${pid===currentPlayerId?" (jij)":""}</strong><span>${p.ready?"✅ READY":"⏳ wacht"}</span></div>`).join("")||"Nog geen spelers.";const total=Object.keys(ps).length,ready=Object.values(ps).filter(p=>p.ready).length;$("lobbyStatus").textContent=`${ready}/${total} spelers ready`;renderCard("ownCard",me.card||[],me.marked||{});$("readyBtn").disabled=!!me.ready;$("readyBtn").classList.toggle("readyActive",!!me.ready)}
function showOtherCard(pid){db.ref("rooms/"+currentRoomCode+"/players/"+pid).once("value").then(s=>{const p=s.val();if(!p)return;$("otherCardBox").classList.remove("hidden");$("otherCardTitle").textContent="Kaart van "+(p.name||"Speler");renderCard("otherCard",p.card||[],p.marked||{})})}
window.showOtherCard=showOtherCard;
function renderCard(id,card,marked,clickable=false,round=null){const el=$(id);if(!el)return;el.innerHTML=(card||[]).map((c,i)=>{const m=marked&&marked[i],pickable=clickable&&round&&c===round.colorKey&&c!=="free"&&!m,blocked=clickable&&!pickable&&c!=="free"&&!m;return `<div class="bingoCell ${c==="free"?"free":""} ${pickable?"pickableCell":""} ${blocked?"blockedCell":""}" data-index="${i}">${m?"✅":emoji(c)}</div>`}).join("");if(clickable)el.querySelectorAll(".pickableCell").forEach(cell=>cell.addEventListener("click",()=>pickCell(Number(cell.dataset.index))))}
function renderColor(r){$("colorDisplay").innerHTML=`${r.colorEmoji}<br>${r.colorName}`;$("categoryDisplay").textContent=r.category}
function renderAnswer(room,r){$("answerRoundInfo").textContent=`${r.colorEmoji} ${r.colorName} — ${r.category}`;const existing=room.answers?.[r.id]?.[currentPlayerId];if(existing){$("answerInput").value=existing.answer;$("answerInput").disabled=true;$("submitAnswerBtn").disabled=true;$("answerStatus").textContent="🔒 Antwoord ingeleverd."}else{$("answerInput").disabled=false;$("submitAnswerBtn").disabled=false;$("answerStatus").textContent="Typ je antwoord."}clearInterval(screenTimerInterval);screenTimerInterval=setInterval(()=>{const left=Math.max(0,Math.ceil(((r.deadlineMs||0)-Date.now())/1000));$("screenTimer").textContent="⏱️ "+left+" sec";if(left<=0){clearInterval(screenTimerInterval);$("answerInput").disabled=true;$("submitAnswerBtn").disabled=true;$("answerStatus").textContent="🔒 Tijd voorbij."}},300)}
function submitAnswer(){if(!activeRound||activeRound.status!=="answering")return;db.ref("rooms/"+currentRoomCode+"/answers/"+activeRound.id+"/"+currentPlayerId).set({answer:$("answerInput").value||"",submittedAt:firebase.database.ServerValue.TIMESTAMP}).then(()=>screenShow("screenScore"))}
function renderScore(room){const r=room.currentRound||{},ans=r.correctAnswer,box=$("correctAnswerBox");if(ans){box.classList.remove("hidden");box.innerHTML=`<h3>✅ Juiste Spotify-antwoord</h3><p>🎵 <strong>Track:</strong> ${esc(ans.track||"-")}</p><p>👤 <strong>Artiest:</strong> ${esc(ans.artist||"-")}</p><p>📅 <strong>Jaar:</strong> ${esc(ans.year||"-")}</p><p>💿 <strong>Album:</strong> ${esc(ans.album||"-")}</p>`}else box.classList.add("hidden");const ps=room.players||{},answers=room.answers?.[r.id]||{},cor=room.correct?.[r.id]||{};$("scoreboard").innerHTML=Object.entries(ps).map(([pid,p])=>{const st=r.status==="judged"?cor[pid]:undefined,cls=st===true?"scoreGood":st===false?"scoreBad":"scorePending",icon=st===true?"✅":st===false?"❌":"⏳";return `<div class="scoreCard ${cls}"><div class="scoreName" onclick="showOtherCard('${pid}')">${esc(p.name||"Speler")}${pid===currentPlayerId?" (jij)":""}</div><div class="scoreAnswer">${esc(answers[pid]?.answer||"Geen antwoord")}</div><div class="scoreStatus">${icon}</div></div>`}).join("")}
function renderPick(room,r){const me=room.players?.[currentPlayerId]||{};$("pickInfo").textContent=`Kies 1 ${r.colorEmoji} ${r.colorName} vakje.`;renderCard("pickCard",me.card||[],me.marked||{},true,r)}
function setReady(){db.ref("rooms/"+currentRoomCode+"/players/"+currentPlayerId+"/ready").set(true)}
function checkBingo(marked){const lines=[[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24],[0,5,10,15,20],[1,6,11,16,21],[2,7,12,17,22],[3,8,13,18,23],[4,9,14,19,24],[0,6,12,18,24],[4,8,12,16,20]];return lines.some(line=>line.every(i=>i===12||(marked&&marked[i])))}
function pickCell(i){db.ref("rooms/"+currentRoomCode+"/players/"+currentPlayerId).once("value").then(s=>{const p=s.val()||{},marked=p.marked||{},card=p.card||[];if(card[i]!==activeRound.colorKey||marked[i])return;marked[i]=true;const bingo=checkBingo(marked);return db.ref("rooms/"+currentRoomCode+"/players/"+currentPlayerId).update({marked,bingo,lastPickedRound:activeRound.id,ready:true}).then(()=>{if(bingo)db.ref("rooms/"+currentRoomCode+"/bingos").push({name:currentPlayerName,playerId:currentPlayerId,roundId:activeRound.id,at:firebase.database.ServerValue.TIMESTAMP});screenShow("screenLobby")})})}

// Winner/audio
let audioCtx=null;function activateHostSound(){try{const C=window.AudioContext||window.webkitAudioContext;if(C&&!audioCtx)audioCtx=new C();if(audioCtx&&audioCtx.state==="suspended")audioCtx.resume();hostSoundReady=true;$("hostSoundStatus").textContent="✅ Host-geluid actief."}catch(e){alert(e.message)}}
function playTune(){try{const C=window.AudioContext||window.webkitAudioContext;if(!audioCtx&&C)audioCtx=new C();if(!audioCtx)return;[523,659,784,1046].forEach((f,i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=f;o.connect(g);g.connect(audioCtx.destination);const t=audioCtx.currentTime+i*.18;g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(.3,t+.03);g.gain.exponentialRampToValueAtTime(.001,t+.16);o.start(t);o.stop(t+.18)})}catch(e){}}
function speakWinner(name){try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance("Aiiii mi hende. Speler "+name+" heeft bingo!");u.lang="nl-NL";u.rate=.9;speechSynthesis.speak(u)}catch(e){}}
function confetti(){const cs=["#ffd21f","#ff4f93","#8d35ff","#19a8ff","#62d321","#fff"];for(let i=0;i<90;i++){const p=document.createElement("div");p.className="confettiPiece";p.style.left=Math.random()*100+"vw";p.style.background=pick(cs);document.body.appendChild(p);setTimeout(()=>p.remove(),3500)}}
function showWinner(name){if($("winnerPanel")){$("winnerPanel").classList.remove("hidden");$("winnerMessage").innerHTML="🏆 BINGO!<br>Speler "+esc(name)+" heeft gewonnen!"}if($("hostBingoBox")){$("hostBingoBox").classList.remove("hidden");$("hostBingoMessage").innerHTML="🏆 BINGO!<br>Speler "+esc(name)+" heeft gewonnen!"}confetti();playTune();setTimeout(()=>speakWinner(name),700)}
function listenBingo(room){db.ref("rooms/"+room+"/bingos").on("child_added",s=>{const b=s.val()||{},key=s.key+"_"+(b.roundId||"");if(key===lastBingoKey)return;lastBingoKey=key;localStorage.hb_last_bingo_key=key;showWinner(b.name||"onbekend")})}

// Wire
initFirebase();
$("loginBtn")?.addEventListener("click",login);$("logoutBtn")?.addEventListener("click",logout);$("activateBtn")?.addEventListener("click",activatePlayer);$("csvFile")?.addEventListener("change",handleCsvFile);$("clearCsvBtn")?.addEventListener("click",()=>{delete localStorage.hb_csv_tracks;tracks=[];updateStatus()});$("resetUsedBtn")?.addEventListener("click",()=>{delete localStorage.hb_used;updateStatus()});
$("newRoomBtn")?.addEventListener("click",createRoom);$("activateHostSoundBtn")?.addEventListener("click",activateHostSound);$("startBtn")?.addEventListener("click",startRound);$("playBtn")?.addEventListener("click",playHidden);$("stopBtn")?.addEventListener("click",stopPlayback);$("answerBtn")?.addEventListener("click",showAnswer);$("lockRoundBtn")?.addEventListener("click",lockRound);$("publishResultsBtn")?.addEventListener("click",publishResults);
$("screenJoinBtn")?.addEventListener("click",()=>joinPlayer(false));$("readyBtn")?.addEventListener("click",setReady);$("submitAnswerBtn")?.addEventListener("click",submitAnswer);$("scoreToLobbyBtn")?.addEventListener("click",()=>screenShow("screenLobby"));

handleRedirect().then(updateStatus).catch(e=>showError(e.message));setupPlayer();
const saved=localStorage.hb_host_room;if(saved&&!new URLSearchParams(location.search).get("room")){currentRoomCode=saved;showHostRoom(saved);listenHost(saved);listenBingo(saved)}
